# This workflow will install Python dependencies, run tests and lint with a variety of Python versions
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-python-with-github-actions

name: Python package

on:
  pull_request:
    branches: [ master, develop ]
    paths-ignore:
      - 'README.md'
      - 'docs/**'
  schedule:
    - cron: '0 0 * * *'

jobs:
  build:

    runs-on: ubuntu-18.04
    strategy:
      matrix:
        python-version: [ '3.7', '3.8', '3.9' ]

    steps:
      - uses: actions/checkout@v2

      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v2
        with:
          python-version: ${{ matrix.python-version }}

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install tox
          pip install --upgrade -r requirements.txt

#      - name: Run tox
#        run: tox -v
#
#      - name: Upload coverage to Codecov
#        uses: codecov/codecov-action@v1
#        with:
#          token: ${{ secrets.CODECOV_TOKEN }}
#          file: ./coverage.xml
#          flags: unittests
